spring.application.name=integration

#spring.rabbitmq.addresses=localhost:5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

spring.rabbitmq.stream.username=user
spring.rabbitmq.stream.password=password
spring.rabbitmq.stream.host=localhost
spring.rabbitmq.stream.name=stream-requests
spring.rabbitmq.listener.type=stream
